### ISSUE TITLE
The OMEMO session isn't automatically connecting or refreshing after you accept a friend

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#313]
If you manually hit ‘refresh session’ the key will show up and you are be able to chat.

**Comment by N-Pex** [comment]
I think this is fixed now in https://github.com/ChatSecure/ChatSecure-iOS/pull/760, at least in my testing.

**Comment by cstiens** [comment]
Tested this today and still some issues with getting the OMEMO session started. I have to refresh the session to be able to chat.

**Comment by chrisballinger** [comment]
I didn't think the refresh session button did anything related to OMEMO,
only OTR. We do attempt to refresh the OMEMO devicelist on viewWillAppear,
I think.

**Comment by cstiens** [comment]
Still have issues with OMEMO session starting right away.  It did help to hit the refresh session button. Happening on all devices tested (iphone 7, iphone 6 and ipad).

**Comment by cstiens** [comment]
We'll test this outside of the account migration scenario to see if it's a bug in 'normal' use cases.

**Comment by N-Pex** [comment]
@cstiens Lots of small fixes to this, this should work now in version 85!
