### ISSUE TITLE
All messages disappearing in the chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-iOS#488]
@N-Pex I'm not sure if this is related to the issues with the supplementary view, but when Rosa and I were chatting this morning, all of her chats would disappear. (Side note: I was on my Android phone, and didn't ever have them disappear.)

She quit and reopened that app and it was resolved.

Many times, when Rosa is chatting with a contact, the messages will disappear when she sends a message. When she scrolls, they all appear again.

**Comment by N-Pex** [comment]
Doesn't sound like related to supplementary views, but sounds like the problem with screen rotation that was fixed pretty recently. Is she on the latest build?

**Comment by N-Pex** [comment]
I saw this problem when switching between chats. Fixed a bug related to the scroll position not being reset, so please retest in version 114.

**Comment by tiffrobo** [comment]
Messages are no longer disappearing like they were. We have seen brief disappearances, but they render back within seconds.

**Comment by chrisballinger** [comment]
I'm still seeing this. Both the scrolling to wrong place, and messages disappearing entirely until app is restarted.

**Comment by tiffrobo** [comment]
@chrisballinger What steps are you taking when you see the messages disappear? I will do some more testing.

**Comment by chrisballinger** [comment]
It seems to mostly happen when I send messages in conversations with large message history

**Comment by cstiens** [comment]
@tiffrobo will you test this one?

**Comment by tiffrobo** [comment]
So far so good! Not seeing this in build 125. 

Device: iPhone 7
OS: 11.2.2
Device: iPad
OS: 10.3.2
Build: version 125

**Comment by cstiens** [comment]
Rosa has seen this in build 125. I'm moving it to the backlog, since it's likely a by-product of our chat view and can be fixed by closing and re-opening the app.
